services:
  - type: web
    name: mi-app-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn nombre_proyecto.wsgi:application"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
